### ISSUE TITLE
Use with Redshift

### ISSUE THREAD

**Issue by bbstilson** [tpolecat/skunk#229]
```
🔥  Postgres FATAL 42704 raised in set_config_option (/home/ec2-user/padb/src/pg/src/backend/utils/misc/guc.c:23873)
🔥  
🔥    Problem: Unrecognized configuration parameter "IntervalStyle".
```

IntervalStyle isn't supported by Redshift. I found some documentation that states the default parameters are not overridable at the moment, but I'd be happy to take a crack at this with some guidance in the right direction.

For example, this is what a postgres library for Julia offers: https://github.com/invenia/LibPQ.jl/blob/dc200995d2c5c928952dfe7b80d7aa70a8421956/docs/src/pages/faq.md

**Comment by tpolecat** [comment]
Yep, we can provide a way to do this if you'd like to give it a go. 

The startup parameters are defined in `StartupMessage.scala`, which is referenced as a constant in the message encoder. We could instead add a `Map[String, String]` member to `StartupMessage` and encode this instead. The refactor will just be piping the parameter all the way out to the `Session` factory methods, at which point you can default it to `StartupMessage.ConnectionProperties` ... which you should move onto `Session` and call it `DefaultConnectionProperties` (be sure to update `Sessions.md` in the `docs` project, which references the constant). This would give you some wiggle room if you want to pass something different to Redshift.

Beyond that I can't really commit to supporting Redshift because there's no obvious way for me to run tests against it, but this change is minor enough and it should unblock you so you can explore a bit more.

**Comment by nbenns** [comment]
I see there is a working solution in the PR but it hasn't been updated since Oct 12th, any thoughts of when it might get merged?
willing to put in some effort if need be.

**Comment by tpolecat** [comment]
I was just looking at this actually. I need to resolve some conflicts but it should be merged later today.
