### ISSUE TITLE
[Question] Any performance benchmark? Difference between doobie (easy-to-use, performance)?

### ISSUE THREAD

**Issue by UkonnRa** [tpolecat/skunk#273]
Hi,

* Do we have a benchmark comparing with the famous database libs? Such as vertx-postgres, doobie and so on?
* What's the difference comparing with doobie, which is also a functional database lib, isn't it?

**Comment by patseev** [comment]
Regarding comparison with doobie.

Doobie works with the JDBC (which is clunky), skunk works with PSQL protocol directly. That leads to code that works as expected more often than with JDBC (_cough datetimes cough_). Also that means that there is an additional support for PSQL-exclusive features such as [channels](https://tpolecat.github.io/skunk/tutorial/Channels.html). Also better error handling due to not relying on JDBC errors, you get direct access to PSQL errors.
Besides that, doobie is battle-tested and is used in production by many companies. Skunk is still in development stage.

**Comment by tpolecat** [comment]
Thanks @patseev, that's all accurate. 

The answer is, we haven't done any performance work yet.
