### ISSUE TITLE
It would've been great if skunk could also support pluggable protocols and dialects

### ISSUE THREAD

**Issue by yuriy-yarosh** [tpolecat/skunk#634]
I'm a ScyllaDB heavy user myself, and even using Skunk in production already.
It would be great if skunk had pluggable protocols and SQL dialects support for DB's like ScyllaDB, MySQL and kSQLdb.
Query/Statement builders can be left the same and most of the existing design approaches and choices should be suitable for the aforementioned DB's.

Any thoughts ?

**Comment by Daenyth** [comment]
Not saying it can't be done, but one of the reasons that skunk is powerful is because it's *not* modular. The api is *exactly* postgres's api, just lifted to cats-effect and fs2.

I feel like the way to go would be to fork skunk, adapt the fork to be fully specialized for scylladb, then after that's done, look at both and see what can possibly be made common - probably there's general concepts, like the twiddle list encoding for example

**Comment by yuriy-yarosh** [comment]
> The api is exactly postgres's api
It could be lifted to a separate lib.
I'm not suggesting making a generic API for all the above, on the contrary, - lift the respective API's the same way skunk did for Postgres.

> like the twiddle list encoding for example
Resource management, query inflation, basic networking and pooling could be reused for sure.

There are also generic protocols, like [Flight SQL](https://arrow.apache.org/blog/2022/02/16/introducing-arrow-flight-sql/) from Apache Arrow available for generalization.

**Comment by yuriy-yarosh** [comment]
@tpolecat Rob, thanks for the quick reply.
Sure thing, created a [fork](https://github.com/bitsnap/scunk) and we'll see how it goes.
Don't want to overcomplicate things, just thought that it might be good initiative from community adoption perspective, but I digress. Anyhow, this fork could be backported if things will work out as I expect (usually they do not).

Sorry for bothering, have a good day.

**Comment by tpolecat** [comment]
> Sorry for bothering, have a good day.

No bother at all, it's just out of scope for my goals here.
