### ISSUE TITLE
Is the skunk in a funk?

### ISSUE THREAD

**Issue by benhutchison** [tpolecat/skunk#697]
I want to ask whether @tpolecat would consider taking on new committers or otherwise changing the maintenance model for skunk to empower others to help maintain it & get a bit more activity flowing.

It's around 6 months since there's been a merge or release in Skunk. 39 open PRs at the time of writing. 

Some of them probably aren't that important, but there's at least [one](https://github.com/tpolecat/skunk/pull/656/files) that is important to me (as the author!) but also [apparently has been copied into at least 2 other codebases because people need it](https://discord.com/channels/632277896739946517/839844929877704785/1006973477787549736).

As a user, I'm nervous about depending on the project despite the excellence of the library. Skunk is amazingly nice to use and it deserves to live. The high discord activity and 1.3 kilostars demonstrates the value in this project from users.

**Comment by mpilquist** [comment]
I’d be happy to help maintain Skunk.

**Comment by fdietze** [comment]
@tpolecat kind reminder to give someone the permissions to maintain the project. @mpilquist has many approving reactions from the community.

**Comment by matthughes** [comment]
I'd also be happy to help with maintenance.

**Comment by sbuzzard** [comment]
i would as well.

**Comment by kubukoz** [comment]
Same :)

**Comment by vbergeron** [comment]
Same for me :rocket:

**Comment by benhutchison** [comment]
Is anyone on this ticket able to get in touch with Rob through other channels, eg work, everyday life, mobile or email? 

I'm guessing he's not aware of the thread atm..

**Comment by mpilquist** [comment]
Rob granted me access today and I’ll start working in PR merges

**Comment by mpilquist** [comment]
Update:
- Merged 30 PRs including all the library & build update PRs (required a few code changes & workarounds but were mostly straightforward)
- Build converted to sbt-typelevel (#705) in order to unblock sbt-paradox upgrade (thanks @armanbilge!)
- Twiddler support on Scala 3 extended to arity 16 (#656) -- PR was updated to use refinements & Scala 3 syntax 
- Existing usage of Scala 3 mirrors was updated to use a more idiomatic style (#706)

All of the above has been released as version 0.3.2, which is binary compatible with 0.3.1.

**Comment by SethTisue** [comment]
The skunk is crunk!

**Comment by benhutchison** [comment]
Unfamiliar with the term "crunk" I had to look it up:

adjective Slang.
excited; full of energy.
drunk and high on drugs.

Not sure which meaning you intended Seth.. ;)

**Comment by SethTisue** [comment]
both meanings intended :-)
